---
language: go

go:
  - 1.4.3
  - 1.5.1

services:
  - etcd
  - sqlite3

branches:
  only:
    - master

before_script:
  - etcdctl mkdir /config
  - |
  etcdctl set /config/go_oauth2_server.json '{
      "AccessTokenLifetime": 3600,
      "RefreshTokenLifetime": 1209600
  }'
script:
  - make install-deps && make test
