version: "2"
services:
  postgres:
    image: "postgres"
    volumes:
      - ./postgres-data:/data
    environment:
      POSTGRES_USER: "go_oauth2_server"
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: "go_oauth2_server"
  etcd:
    depends_on:
      - postgres
    image: "elcolio/etcd"
    volumes:
      - ./etcd-data:/data
  go-oauth2-server:
    depends_on:
      - etcd
      - postgres
    links:
      - etcd
      - postgres
    build:
      context: .
      dockerfile: ./Dockerfile-compose
    image: go-oauth2-server:latest
    container_name: go-oauth2-server
    ports:
      - "8080:8080"
    environment:
      ETCD_ENDPOINTS: "http://etcd:2379"
    command: [go-oauth2-server, runserver]
